const STORAGE_KEY='myLifeDashboardV2';
const DAY_KEYS=['sun','mon','tue','wed','thu','fri','sat'];
const DISPLAY_DAYS=['mon','tue','wed','thu','fri','sat','sun'];
const DAY_LABELS={sun:'Sunday',mon:'Monday',tue:'Tuesday',wed:'Wednesday',thu:'Thursday',fri:'Friday',sat:'Saturday'};
const KEY_TYPES=new Set(['uni','gym','ball','work','rehab','leave']);
const PARTS=[['Morning',5,12],['Afternoon',12,17],['Evening',17,24],['Night',0,5]];
const SLEEP_STAGES=[['5:00 am','1:00 pm'],['4:30 am','12:30 pm'],['4:00 am','12:00 pm'],['3:30 am','11:30 am'],['3:00 am','11:00 am'],['2:30 am','10:30 am'],['2:00 am','10:00 am'],['1:30 am','9:30 am']];
function uid(){return Math.random().toString(36).slice(2,9)}
function ev(start,end,title,type='free',note='',optional=false){return{id:uid(),start,end,title,type,note,optional}}
function ex(name,sets,reps,category,note='',neutral=false,cuff=false,knee=false){return{id:uid(),name,sets,reps,category,note,neutral,cuff,knee}}
function mins(t){if(!t||!/\d\d:\d\d/.test(t))return null;const[h,m]=t.split(':').map(Number);return h*60+m}
function logicalMinutes(t){const m=mins(t);return m==null?9999:(m<300?m+1440:m)}
function fmt(t){if(!t)return'';let[h,m]=t.split(':').map(Number);const ap=h>=12?'pm':'am';h=h%12||12;return `${h}:${String(m).padStart(2,'0')} ${ap}`}
function fmtRange(a,b){return b&&b!==a?`${fmt(a)} – ${fmt(b)}`:fmt(a)}
function dayKeyFromDate(d=new Date()){return DAY_KEYS[d.getDay()]}
function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function doneKey(day,id){return`done:${dateKey()}:${day}:${id}`}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function daysUntil(dateStr){const t=new Date(dateStr+'T12:00:00'),n=new Date();n.setHours(12,0,0,0);return Math.ceil((t-n)/86400000)}
function partOfDay(t){const m=mins(t);if(m==null)return'';for(const[name,start,end]of PARTS){if(start<end&&m>=start*60&&m<end*60)return name;if(start>end&&(m>=start*60||m<end*60))return name}return''}
function currentLogical(){const d=new Date(),m=d.getHours()*60+d.getMinutes();return m<300?m+1440:m}
function untilText(t){const diff=logicalMinutes(t)-currentLogical();if(diff<=0)return'Now / in progress';const h=Math.floor(diff/60),m=diff%60;return h?`in ${h}h${m?` ${m}m`:''}`:`in ${m}m`}
let defaultsData=null;
async function loadDefaults(){const r=await fetch('./defaults.json?v=4.0.0',{cache:'no-store'});if(!r.ok)throw new Error('defaults');defaultsData=await r.json();return defaultsData}
function cloneDefaults(){return JSON.parse(JSON.stringify(defaultsData))}
function migrate(d,b=defaultsData){d.settings={...b.settings,...(d.settings||{})};d.focus={...b.focus,...(d.focus||{})};d.days={...b.days,...(d.days||{})};d.uni=d.uni||b.uni;d.rehab=Array.isArray(d.rehab)?d.rehab:b.rehab;d.gym=d.gym||b.gym;d.sundayGame=d.sundayGame||b.sundayGame;d.currentSleep=Number.isInteger(d.currentSleep)?d.currentSleep:0;d.lowEnergy=!!d.lowEnergy;d.sleepChecks=d.sleepChecks||b.sleepChecks;if(!d.sleepChecks.night)d.sleepChecks.night=b.sleepChecks.night;if(!d.sleepChecks.morning)d.sleepChecks.morning=b.sleepChecks.morning;if(!d.days.sun?.length)buildSunday(d);return d}
async function load(){const defaults=await loadDefaults();try{const raw=localStorage.getItem(STORAGE_KEY);return raw?migrate(JSON.parse(raw),defaults):migrate(defaults,defaults)}catch{return migrate(defaults,defaults)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function persist(msg){save();if(msg)toast(msg)}
function buildSunday(target=data){const start=mins(target.sundayGame),prep=start-80,leave=start-40,arrive=start-25,end=start+60;const tm=v=>{v=(v+1440)%1440;return`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`};target.days.sun=[ev('09:30','09:45','Wake','sleep'),ev('10:00','10:20','Breakfast','food'),ev('10:30','12:00','Light uni / weekly review','uni'),ev('12:00','12:45','Lunch','food'),ev('12:45',tm(prep),'Relax + recover'),ev(tm(start-180),tm(start-150),'Pre-game meal','food','Aim roughly 2.5–3 hours before tip'),ev(tm(prep),tm(leave),'Get dressed + hair + pack bag','free','40 minutes'),ev(tm(leave),tm(arrive),'Leave home for game','leave','~15-minute drive; arrive 25 minutes before tip'),ev(tm(arrive),target.sundayGame,'Warm up / stretch / shoot','ball'),ev(target.sundayGame,tm(end),'Basketball game','ball','Two 20-minute halves; you often play 35–40+ minutes'),ev(tm(end),tm(end+15),'Drive home'),ev(tm(end+15),tm(end+60),'Shower + dinner + recover','food'),ev('01:00','01:30','Bed wind-down','sleep'),ev('01:30','01:31','Sleep target','sleep')]}
let data=null,currentDay=dayKeyFromDate(),currentView='today',currentSession='A',fitnessTab='gym',weekMode='key',deferredPrompt=null,sortables=[];
function isDone(day,id){return!!data[doneKey(day,id)]}
function setDone(day,id,v){data[doneKey(day,id)]=v;persist()}
function dayEvents(day){return data.days[day]||[]}
function visibleEvents(day){return dayEvents(day).filter(e=>!(data.lowEnergy&&e.optional))}
function chronological(events){return[...events].sort((a,b)=>logicalMinutes(a.start)-logicalMinutes(b.start))}
function progress(day){const evs=visibleEvents(day),done=evs.filter(e=>isDone(day,e.id)).length;return{done,total:evs.length}}
function toast(text){const t=document.getElementById('toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1600)}
function destroySortables(){sortables.forEach(s=>{try{s.destroy()}catch{}});sortables=[]}
function makeSortable(el,options){if(!window.Sortable)return;sortables.push(Sortable.create(el,{animation:180,ghostClass:'sortable-ghost',chosenClass:'sortable-chosen',...options}))}
function switchView(v){currentView=v;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));renderCurrent();window.scrollTo({top:0,behavior:'smooth'})}
function renderCurrent(){destroySortables();if(currentView==='today')renderToday();if(currentView==='week')renderWeek();if(currentView==='uni')renderUni();if(currentView==='fitness')renderFitness();if(currentView==='sleep')renderSleep();if(currentView==='settings')renderSettings()}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
function renderDaySwitcher(){const wrap=document.getElementById('todayTabs');wrap.innerHTML='';const today=new Date();DISPLAY_DAYS.forEach(day=>{const targetIndex=DAY_KEYS.indexOf(day);const offset=(targetIndex-today.getDay()+7)%7;const d=new Date(today);d.setDate(today.getDate()+offset);const p=progress(day);const b=document.createElement('button');b.className='day-pill'+(day===currentDay?' active':'');b.innerHTML=`<span class="day-name">${DAY_LABELS[day].slice(0,3)}</span><span class="day-num">${d.getDate()}</span><span class="day-done">${p.done}/${p.total}</span>`;b.onclick=()=>{currentDay=day;renderToday()};wrap.appendChild(b)})}
function nextEvent(day,type=null){const evs=chronological(visibleEvents(day).filter(e=>!type||e.type===type));if(day!==dayKeyFromDate())return evs[0]||null;const now=currentLogical();return evs.find(e=>logicalMinutes(e.end||e.start)>=now)||null}
function renderToday(){destroySortables();renderDaySwitcher();const today=currentDay===dayKeyFromDate();const date=today?new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}):DAY_LABELS[currentDay];document.getElementById('todayDate').textContent=date;document.getElementById('todayHeading').textContent=today?'Today':DAY_LABELS[currentDay];document.getElementById('todaySubtitle').textContent=today?'Your schedule, one step at a time.':'Previewing this day. Changes save automatically.';document.getElementById('lowEnergyToggle').checked=data.lowEnergy;document.getElementById('todayFocus').textContent=data.focus[currentDay]||'No main goal set';const n=nextEvent(currentDay),l=nextEvent(currentDay,'leave');document.getElementById('nextTitle').textContent=n?n.title:'Nothing else planned';document.getElementById('nextCountdown').textContent=n?(today?`${fmtRange(n.start,n.end)} · ${untilText(n.start)}`:fmtRange(n.start,n.end)):'You have some breathing room.';document.getElementById('nextLeave').textContent=l?fmt(l.start):'Nothing coming up';document.getElementById('nextLeaveCountdown').textContent=l?`${l.title}${today?' · '+untilText(l.start):''}`:'No leave-home block remaining.';const p=progress(currentDay);document.getElementById('todayProgress').textContent=`${p.done} of ${p.total} done`;document.getElementById('todayProgressBar').style.width=p.total?`${Math.round(p.done/p.total*100)}%`:'0%';const wrap=document.getElementById('todayTimeline');wrap.innerHTML='';let lastPart='';visibleEvents(currentDay).forEach(e=>{const part=partOfDay(e.start);if(part&&part!==lastPart){const label=document.createElement('div');label.className='part-label';label.textContent=part;wrap.appendChild(label);lastPart=part}wrap.appendChild(eventRow(currentDay,e))});makeSortable(wrap,{handle:'.drag-handle',draggable:'.event-row',onEnd(){const ids=[...wrap.querySelectorAll('.event-row')].map(x=>x.dataset.id);const original=dayEvents(currentDay);const map=new Map(original.map(x=>[x.id,x]));const visibleSet=new Set(ids);let pointer=0;data.days[currentDay]=original.map(item=>visibleSet.has(item.id)?map.get(ids[pointer++]):item);persist('Schedule reordered');renderToday()}})}
