function eventRow(day,e){const row=document.createElement('div');row.className='event-row'+(isDone(day,e.id)?' done':'');row.dataset.id=e.id;row.innerHTML=`<button class="drag-handle" aria-label="Drag to reorder" title="Drag to reorder">⠿</button><div class="event-time"><strong>${escapeHtml(fmt(e.start))}</strong><span>${e.end?escapeHtml(fmt(e.end)):''}</span></div><div class="event-main"><div class="event-top"><span class="category-dot dot-${escapeHtml(e.type||'free')}"></span><div class="event-title">${escapeHtml(e.title)}</div>${e.optional?'<span class="optional-badge">Optional</span>':''}</div>${e.note?`<div class="event-note">${escapeHtml(e.note)}</div>`:''}</div><div class="event-actions"><button class="row-button check-button ${isDone(day,e.id)?'done-button':''}" title="${isDone(day,e.id)?'Mark not done':'Mark done'}">${isDone(day,e.id)?'↶':'✓'}</button><button class="row-button edit-button" title="Edit">•••</button></div>`;row.querySelector('.check-button').onclick=()=>{setDone(day,e.id,!isDone(day,e.id));renderToday()};row.querySelector('.edit-button').onclick=()=>openEvent(day,e.id);return row}
function renderWeek(){destroySortables();const wrap=document.getElementById('weekGrid');wrap.innerHTML='';DISPLAY_DAYS.forEach(day=>{const all=chronological(visibleEvents(day));const shown=weekMode==='key'?all.filter(e=>KEY_TYPES.has(e.type)):all;const card=document.createElement('article');card.className='week-day-card'+(day===dayKeyFromDate()?' current-day':'');card.innerHTML=`<div class="week-day-header"><div><div class="week-day-title">${DAY_LABELS[day]}</div><div class="week-day-goal">${escapeHtml(data.focus[day]||'')}</div></div><button class="open-day">Open day</button></div><div class="week-events">${shown.map(e=>`<div class="week-event"><span class="week-event-time">${escapeHtml(fmt(e.start))}</span><span class="category-dot dot-${escapeHtml(e.type||'free')}"></span><span class="week-event-title">${escapeHtml(e.title)}</span></div>`).join('')||'<div class="week-more">No blocks in this view.</div>'}</div>`;card.querySelector('.open-day').onclick=()=>{currentDay=day;switchView('today')};wrap.appendChild(card)})}
document.querySelectorAll('[data-week-mode]').forEach(b=>b.onclick=()=>{weekMode=b.dataset.weekMode;document.querySelectorAll('[data-week-mode]').forEach(x=>x.classList.toggle('active',x===b));renderWeek()});
function renderUni(){destroySortables();const wrap=document.getElementById('uniGrid');wrap.innerHTML='';Object.entries(data.uni).forEach(([code,s])=>{const left=daysUntil(s.due),card=document.createElement('article');card.className='subject-card';card.innerHTML=`<div class="subject-head"><div><div class="subject-code">${escapeHtml(s.name)}</div><div class="subject-due">Due ${new Date(s.due+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}</div></div><div class="days-left">${left} days left</div></div><div class="subject-progress"><div class="progress-track"><div style="width:${Math.max(0,Math.min(100,s.progress))}%"></div></div><strong>${s.progress}%</strong></div><div class="task-list" data-code="${code}"></div><div class="subject-actions"><button class="add-task-button">＋ Add next action</button><input class="progress-input" type="number" min="0" max="100" value="${s.progress}" aria-label="Progress percent"></div>`;const list=card.querySelector('.task-list');s.tasks.forEach(t=>{const item=document.createElement('div');item.className='task-item';item.dataset.id=t.id;item.innerHTML=`<button class="task-drag" title="Drag to reorder">⠿</button><label class="task-check-row"><input type="checkbox" ${t.done?'checked':''}><span class="task-text ${t.done?'done':''}">${escapeHtml(t.text)}</span></label><button class="task-edit">•••</button>`;item.querySelector('input').onchange=x=>{t.done=x.target.checked;persist();renderUni()};item.querySelector('.task-edit').onclick=()=>editUniTask(code,t.id);list.appendChild(item)});card.querySelector('.add-task-button').onclick=()=>addUniTask(code);card.querySelector('.progress-input').onchange=e=>{s.progress=Math.max(0,Math.min(100,Number(e.target.value)||0));persist('Progress updated');renderUni()};wrap.appendChild(card);makeSortable(list,{handle:'.task-drag',draggable:'.task-item',onEnd(){const ids=[...list.querySelectorAll('.task-item')].map(x=>x.dataset.id);const m=new Map(s.tasks.map(t=>[t.id,t]));s.tasks=ids.map(id=>m.get(id));persist('Tasks reordered')}})})}
function addUniTask(code){const text=prompt(`Add the next action for ${code}:`);if(text?.trim()){data.uni[code].tasks.push({id:uid(),text:text.trim(),done:false});persist('Task added');renderUni()}}
function editUniTask(code,id){const s=data.uni[code],t=s.tasks.find(x=>x.id===id),v=prompt('Edit next action:',t.text);if(v===null)return;if(!v.trim()){if(confirm('Delete this action?'))s.tasks=s.tasks.filter(x=>x.id!==id)}else t.text=v.trim();persist('Task updated');renderUni()}
function renderFitness(){destroySortables();document.querySelectorAll('[data-fitness-tab]').forEach(b=>b.classList.toggle('active',b.dataset.fitnessTab===fitnessTab));document.querySelectorAll('.fitness-panel').forEach(x=>x.classList.toggle('active',x.id==='fitness'+fitnessTab[0].toUpperCase()+fitnessTab.slice(1)));if(fitnessTab==='gym')renderGym();if(fitnessTab==='basketball')renderBasketball();if(fitnessTab==='rehab')renderRehab()}
document.querySelectorAll('[data-fitness-tab]').forEach(b=>b.onclick=()=>{fitnessTab=b.dataset.fitnessTab;renderFitness()});
function renderGym(){document.querySelectorAll('[data-session]').forEach(b=>b.classList.toggle('active',b.dataset.session===currentSession));const s=data.gym[currentSession];document.getElementById('gymTitle').textContent=currentSession==='A'?'Monday · Gym A':'Wednesday · Gym B';document.getElementById('gymFocus').textContent=s.focus;const list=document.getElementById('exerciseList');list.innerHTML='';s.exercises.forEach(e=>{const row=document.createElement('div');row.className='exercise-row';row.dataset.id=e.id;row.innerHTML=`<button class="drag-handle" title="Drag to reorder">⠿</button><div><div class="exercise-name">${escapeHtml(e.name)}</div><div class="exercise-detail">${escapeHtml([e.category,e.note,e.neutral?'neutral grip':'',e.cuff?'cuff-friendly':'',e.knee?'knee/rehab':''].filter(Boolean).join(' · '))}</div></div><div class="exercise-stat"><span>Sets</span><strong>${escapeHtml(e.sets||'—')}</strong></div><div class="exercise-stat"><span>Reps</span><strong>${escapeHtml(e.reps||'—')}</strong></div><div class="event-actions"><button class="row-button">•••</button></div>`;row.querySelector('.row-button').onclick=()=>openExercise(e.id);list.appendChild(row)});makeSortable(list,{handle:'.drag-handle',draggable:'.exercise-row',onEnd(){const ids=[...list.querySelectorAll('.exercise-row')].map(x=>x.dataset.id),m=new Map(s.exercises.map(x=>[x.id,x]));s.exercises=ids.map(id=>m.get(id));persist('Workout reordered')}})}
document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{currentSession=b.dataset.session;renderGym()});
function renderBasketball(){document.getElementById('sundayGame').value=data.sundayGame;const s=mins(data.sundayGame),tm=v=>{v=(v+1440)%1440;return`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`};document.getElementById('gameCalc').innerHTML=`<div class="timing-chip"><span>Get ready</span><strong>${fmt(tm(s-80))}</strong></div><div class="timing-chip"><span>Leave</span><strong>${fmt(tm(s-40))}</strong></div><div class="timing-chip"><span>Arrive</span><strong>${fmt(tm(s-25))}</strong></div>`}
document.getElementById('sundayGame').onchange=e=>{data.sundayGame=e.target.value;buildSunday();persist('Game time updated');renderBasketball()};
function renderRehab(){const wrap=document.getElementById('rehabChecklist');wrap.innerHTML='';data.rehab.forEach(r=>{const item=document.createElement('div');item.className='task-item';item.innerHTML=`<span></span><label class="task-check-row"><input type="checkbox" ${r.done?'checked':''}><span class="task-text ${r.done?'done':''}">${escapeHtml(r.text)}</span></label><button class="task-edit">•••</button>`;item.querySelector('input').onchange=e=>{r.done=e.target.checked;persist();renderRehab()};item.querySelector('.task-edit').onclick=()=>{const v=prompt('Edit rehab item:',r.text);if(v?.trim()){r.text=v.trim();persist('Rehab updated');renderRehab()}};wrap.appendChild(item)})}
function renderSleep(){const stage=Math.max(0,Math.min(SLEEP_STAGES.length-1,data.currentSleep));document.getElementById('currentSleepBed').textContent=SLEEP_STAGES[stage][0];document.getElementById('currentSleepWake').textContent=SLEEP_STAGES[stage][1];const wrap=document.getElementById('sleepStages');wrap.innerHTML='';SLEEP_STAGES.forEach((x,i)=>{const row=document.createElement('button');row.className='sleep-step'+(i===stage?' active':i<stage?' done':'');row.innerHTML=`<span class="step-dot">${i<stage?'✓':i+1}</span><span class="step-name">${i===SLEEP_STAGES.length-1?'Target':i===0?'Start':`Step ${i+1}`}</span><span class="step-time">${x[0]} → ${x[1]}</span>`;row.onclick=()=>{data.currentSleep=i;persist('Sleep stage updated');renderSleep()};wrap.appendChild(row)});renderSimpleList('nightChecklist',data.sleepChecks.night);renderSimpleList('morningChecklist',data.sleepChecks.morning)}
function renderSimpleList(id,items){const wrap=document.getElementById(id);wrap.innerHTML='';items.forEach(r=>{const item=document.createElement('div');item.className='task-item';item.innerHTML=`<span></span><label class="task-check-row"><input type="checkbox" ${r.done?'checked':''}><span class="task-text ${r.done?'done':''}">${escapeHtml(r.text)}</span></label><button class="task-edit">•••</button>`;item.querySelector('input').onchange=e=>{r.done=e.target.checked;persist();renderSleep()};item.querySelector('.task-edit').onclick=()=>{const v=prompt('Edit item:',r.text);if(v?.trim()){r.text=v.trim();persist('Updated');renderSleep()}};wrap.appendChild(item)})}
document.getElementById('nextSleepStage').onclick=()=>{if(data.currentSleep<SLEEP_STAGES.length-1){data.currentSleep++;persist('Moved to next stage');renderSleep()}};
function renderSettings(){for(const k of ['workDrive','gymDrive','ballDrive','workPrep','sportPrep'])document.getElementById(k).value=data.settings[k]}
document.getElementById('saveSettings').onclick=()=>{for(const k of ['workDrive','gymDrive','ballDrive','workPrep','sportPrep'])data.settings[k]=Math.max(0,Number(document.getElementById(k).value)||0);persist('Settings saved')};
const eventDialog=document.getElementById('eventDialog');
function openEvent(day,id=null){const e=id?data.days[day].find(x=>x.id===id):ev('10:00','10:30','','free');document.getElementById('eventDialogTitle').textContent=id?'Edit block':'Add block';document.getElementById('eventDay').value=day;document.getElementById('eventId').value=id||'';document.getElementById('eventStart').value=e.start;document.getElementById('eventEnd').value=e.end;document.getElementById('eventTitle').value=e.title;document.getElementById('eventType').value=e.type;document.getElementById('eventOptional').checked=!!e.optional;document.getElementById('eventNote').value=e.note||'';document.getElementById('deleteEvent').style.visibility=id?'visible':'hidden';eventDialog.showModal()}
document.getElementById('eventForm').onsubmit=e=>{e.preventDefault();const day=document.getElementById('eventDay').value,id=document.getElementById('eventId').value,obj={id:id||uid(),start:document.getElementById('eventStart').value,end:document.getElementById('eventEnd').value,title:document.getElementById('eventTitle').value.trim(),type:document.getElementById('eventType').value,optional:document.getElementById('eventOptional').checked,note:document.getElementById('eventNote').value.trim()};if(!obj.title||!obj.start)return;if(id){const i=data.days[day].findIndex(x=>x.id===id);data.days[day][i]=obj}else data.days[day].push(obj);persist('Block saved');eventDialog.close();renderToday()};
['cancelEvent','cancelEvent2'].forEach(id=>document.getElementById(id).onclick=()=>eventDialog.close());document.getElementById('deleteEvent').onclick=()=>{const day=document.getElementById('eventDay').value,id=document.getElementById('eventId').value;if(id&&confirm('Delete this block?')){data.days[day]=data.days[day].filter(x=>x.id!==id);persist('Block deleted');eventDialog.close();renderToday()}};
const exerciseDialog=document.getElementById('exerciseDialog');
function openExercise(id=null){const e=id?data.gym[currentSession].exercises.find(x=>x.id===id):ex('','3','8–12','Upper body');document.getElementById('exerciseDialogTitle').textContent=id?'Edit exercise':'Add exercise';document.getElementById('exerciseId').value=id||'';document.getElementById('exerciseName').value=e.name;document.getElementById('exerciseSets').value=e.sets;document.getElementById('exerciseReps').value=e.reps;document.getElementById('exerciseCategory').value=e.category;document.getElementById('exerciseNeutral').checked=!!e.neutral;document.getElementById('exerciseCuff').checked=!!e.cuff;document.getElementById('exerciseKnee').checked=!!e.knee;document.getElementById('exerciseNote').value=e.note||'';document.getElementById('deleteExercise').style.visibility=id?'visible':'hidden';exerciseDialog.showModal()}
document.getElementById('exerciseForm').onsubmit=e=>{e.preventDefault();const id=document.getElementById('exerciseId').value,obj={id:id||uid(),name:document.getElementById('exerciseName').value.trim(),sets:document.getElementById('exerciseSets').value.trim(),reps:document.getElementById('exerciseReps').value.trim(),category:document.getElementById('exerciseCategory').value,neutral:document.getElementById('exerciseNeutral').checked,cuff:document.getElementById('exerciseCuff').checked,knee:document.getElementById('exerciseKnee').checked,note:document.getElementById('exerciseNote').value.trim()};if(!obj.name)return;if(id){const i=data.gym[currentSession].exercises.findIndex(x=>x.id===id);data.gym[currentSession].exercises[i]=obj}else data.gym[currentSession].exercises.push(obj);persist('Exercise saved');exerciseDialog.close();renderGym()};
['cancelExercise','cancelExercise2'].forEach(id=>document.getElementById(id).onclick=()=>exerciseDialog.close());document.getElementById('deleteExercise').onclick=()=>{const id=document.getElementById('exerciseId').value;if(id&&confirm('Delete this exercise?')){data.gym[currentSession].exercises=data.gym[currentSession].exercises.filter(x=>x.id!==id);persist('Exercise deleted');exerciseDialog.close();renderGym()}};
document.getElementById('addTodayBtn').onclick=()=>openEvent(currentDay);document.getElementById('mobileAddBtn').onclick=()=>{switchView('today');openEvent(currentDay)};document.getElementById('addExerciseBtn').onclick=()=>openExercise();document.getElementById('lowEnergyToggle').onchange=e=>{data.lowEnergy=e.target.checked;persist(e.target.checked?'Optional blocks hidden':'Optional blocks shown');renderToday()};document.getElementById('editDayFocusBtn').onclick=()=>{const v=prompt('Main goal for '+DAY_LABELS[currentDay]+':',data.focus[currentDay]||'');if(v!==null){data.focus[currentDay]=v.trim();persist('Main goal updated');renderToday()}};
function backup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='life-dashboard-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.getElementById('exportBtn').onclick=backup;document.getElementById('settingsBackup').onclick=backup;document.getElementById('importBtn').onclick=()=>document.getElementById('importFile').click();document.getElementById('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{data=migrate(JSON.parse(await f.text()));persist('Backup restored');renderCurrent()}catch{alert('That backup file could not be read.')}e.target.value=''};document.getElementById('resetApp').onclick=()=>{if(confirm('Reset every saved change in this app?')){data=migrate(cloneDefaults());buildSunday();persist('App reset');renderCurrent()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').hidden=false});document.getElementById('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.getElementById('installBtn').hidden=true};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js?v=4').catch(()=>{}));
async function init(){data=await load();renderCurrent()}
init().catch(()=>{document.body.innerHTML='<div style="padding:40px;font-family:system-ui">Could not load the dashboard. Refresh the page.</div>'});
